CREATE TABLE DE_TEMPLATE_SHEET_CONFIG
(
    TEMPLATE_SHEET_CONFIG_ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TEMPLATE_CONFIG_ID bigint NOT NULL COMMENT 'DE_TEMPLATE_CONFIG.TEMPLATE_CONFIG_ID模板配置id',
    SHEET_NO bigint NOT NULL COMMENT 'sheet页下标',
    SHEET_CONFIG_NAME varchar(30) NOT NULL COMMENT 'sheet配置名称',
    TB_NAME varchar(50) COMMENT '数据库表名',
    MODEL_NAME varchar(100) COMMENT 'JAVA类名。注：是所在包路径',
    DATA_SOURCE_ID bigint COMMENT '数据源Id',
    BATCH_COUNT bigint COMMENT '每batchCount条为一批存储数据库',
    AUTO_UPDATE varchar(1) DEFAULT 'Y' NOT NULL COMMENT '程序是否自动更新',
    UPDATE_WAY varchar(30) DEFAULT 'INSERT' NOT NULL COMMENT '更新方式，默认插入',
    UNIQUE_TB_COLNAMES varchar(255) COMMENT '指定unique数据库字段名',
    HEAD_ROW_NUMBER bigint DEFAULT 1 NOT NULL COMMENT '头底部所在行号（从1开始...）',
    ENABLE_FLAG varchar(1) DEFAULT 'Y' NOT NULL COMMENT '是否启用',
    OBJECT_VERSION_NUMBER bigint default '1'                 null,
    REQUEST_ID            bigint default '-1'                null,
    PROGRAM_ID            bigint default '-1'                null,
    CREATED_BY            bigint default '-1'                null,
    CREATION_DATE         datetime default CURRENT_TIMESTAMP null,
    LAST_UPDATED_BY       bigint default '-1'                null,
    LAST_UPDATE_DATE      datetime default CURRENT_TIMESTAMP null,
    LAST_UPDATE_LOGIN     bigint default '-1'                null,
    ATTRIBUTE_CATEGORY    varchar(30)                        null,
    ATTRIBUTE1            varchar(240)                       null,
    ATTRIBUTE2            varchar(240)                       null,
    ATTRIBUTE3            varchar(240)                       null,
    ATTRIBUTE4            varchar(240)                       null,
    ATTRIBUTE5            varchar(240)                       null,
    ATTRIBUTE6            varchar(240)                       null,
    ATTRIBUTE7            varchar(240)                       null,
    ATTRIBUTE8            varchar(240)                       null,
    ATTRIBUTE9            varchar(240)                       null,
    ATTRIBUTE10           varchar(240)                       null,
    ATTRIBUTE11           varchar(240)                       null,
    ATTRIBUTE12           varchar(240)                       null,
    ATTRIBUTE13           varchar(240)                       null,
    ATTRIBUTE14           varchar(240)                       null,
    ATTRIBUTE15           varchar(240)                       null
);
ALTER TABLE DE_TEMPLATE_SHEET_CONFIG COMMENT = '模板Sheet页配置';