CREATE TABLE DE_TEMPLATE_COL_CONFIG
(
    TEMPLATE_COL_CONFIG_ID bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TEMPLATE_SHEET_CONFIG_ID bigint NOT NULL COMMENT '模板Sheet页配置id. DE_TEMPLATE_SHEET_CONFIG.TEMPLATE_SHEET_CONFIG_ID',
    CELL_NO bigint NOT NULL COMMENT '对应列号',
    TB_COLUMN_NAME varchar(30) COMMENT '数据库字段名',
    TB_COLUMN_COMMIT varchar(50) COMMENT '数据库字段描述',
    CELL_TYPE varchar(30) DEFAULT 'STRING' NOT NULL COMMENT '列类型',
    CELL_FORMAT VARCHAR(30) COMMENT '列格式掩码',
    CELL_MAX_LENGTH bigint COMMENT '列最大长度',
    MAX VARCHAR(50) COMMENT '最大值',
    MIN varchar(50) COMMENT '最小值',
    REQUIRED_FLAG varchar(1) DEFAULT 'N' NOT NULL COMMENT '是否必填',
    OBJECT_VERSION_NUMBER bigint default '1'                 null,
    REQUEST_ID            bigint default '-1'                null,
    PROGRAM_ID            bigint default '-1'                null,
    CREATED_BY            bigint default '-1'                null,
    CREATION_DATE         datetime default CURRENT_TIMESTAMP null,
    LAST_UPDATED_BY       bigint default '-1'                null,
    LAST_UPDATE_DATE      datetime default CURRENT_TIMESTAMP null,
    LAST_UPDATE_LOGIN     bigint default '-1'                null,
    ATTRIBUTE_CATEGORY    varchar(30)                        null,
    ATTRIBUTE1            varchar(240)                       null,
    ATTRIBUTE2            varchar(240)                       null,
    ATTRIBUTE3            varchar(240)                       null,
    ATTRIBUTE4            varchar(240)                       null,
    ATTRIBUTE5            varchar(240)                       null,
    ATTRIBUTE6            varchar(240)                       null,
    ATTRIBUTE7            varchar(240)                       null,
    ATTRIBUTE8            varchar(240)                       null,
    ATTRIBUTE9            varchar(240)                       null,
    ATTRIBUTE10           varchar(240)                       null,
    ATTRIBUTE11           varchar(240)                       null,
    ATTRIBUTE12           varchar(240)                       null,
    ATTRIBUTE13           varchar(240)                       null,
    ATTRIBUTE14           varchar(240)                       null,
    ATTRIBUTE15           varchar(240)                       null
);
ALTER TABLE DE_TEMPLATE_COL_CONFIG COMMENT = '模板列详细配置';
